services:
  machineH1A:
    build:
      context: ./machineH1A
      dockerfile: Dockerfile
    image: machineh1a
    container_name: machineH1A
    restart: unless-stopped
    ports:
      - "10001:80"    # Web (Reflex Gallery Exploit)
    networks:
      - h1_network

  machineH1B:
    build:
      context: ./machineH1B
      dockerfile: Dockerfile
    image: machineh1b
    container_name: machineH1B
    restart: unless-stopped
    ports:
      - "10002:6379"  # Redis (Unauthenticated)
      - "10003:22"    # SSH (Key Injection Entry)
    networks:
      - h1_network

  machineH1C:
    build:
      context: ./machineH1C
      dockerfile: Dockerfile
    image: machineh1c
    container_name: machineH1C
    restart: unless-stopped
    ports:
      - "10004:80"    # Web (Command Injection / Ping Tool)
    networks:
      - h1_network

networks:
  h1_network:
    driver: bridge
