services:
  machineH8A:
    build:
      context: ./machineH8A
      dockerfile: Dockerfile
    image: machineh8a
    restart: unless-stopped
    ports:
      - "10070:80"      # PHPMyAdmin root:blank
    networks:
      - h8_network

  machineH8B:
    build:
      context: ./machineH8B
      dockerfile: Dockerfile
    image: machineh8b
    restart: unless-stopped
    ports:
      - "10071:5000"    # Flask/Jinja2 SSTI
    networks:
      - h8_network

  machineH8C:
    build:
      context: ./machineH8C
      dockerfile: Dockerfile
    image: machineh8c
    restart: unless-stopped
    ports:
      - "10072:8000"    # Laravel Debug CVE-2021-3129
    networks:
      - h8_network

networks:
  h8_network:
    driver: bridge
